import glob
import json
import re
from collections import defaultdict


DATA_PATH = "results"
JS_PATH = "../../src/data/scalingData.js"
REGEX = r"\[X-Task Eval \(cc12m\)\] ([^-\s]+)->([^-\s]+)"

# graph[pct][X][Y] = loss_value
graph = defaultdict(lambda: defaultdict(dict))

for file in glob.glob(f"{DATA_PATH}/*/*.json"):
    with open(file, "r") as f:
        data = json.load(f)
    exp_name = file.split("/")[-2]
    data_pct = int(exp_name.replace("pct", ""))
    for key, value in data.items():
        match = re.match(REGEX, key)
        if match:
            X = match.group(1)
            Y = match.group(2)
            graph[data_pct][X][Y] = value

# Collect ordered X/Y label sets (preserve insertion order across all pcts)
all_pcts = sorted(graph.keys())
x_labels_set, y_labels_set = [], []
for pct in all_pcts:
    for x in graph[pct]:
        if x not in x_labels_set:
            x_labels_set.append(x)
    for x in graph[pct]:
        for y in graph[pct][x]:
            if y not in y_labels_set:
                y_labels_set.append(y)

X_LABELS = x_labels_set
Y_LABELS = y_labels_set

PALETTE = [
    '#6c8ef5', '#f472b6', '#34d399', '#fbbf24',
    '#a78bfa', '#fb923c', '#22d3ee', '#e879f9',
]

def js_str(s):
    return f"'{s}'"

lines = []
lines.append("/**")
lines.append(" * Scaling trends data — auto-generated by compile2js.py")
lines.append(" * x = data scale (% of CC12M), y = cross-task loss")
lines.append(" */")
lines.append("")
lines.append(f"export const X_LABELS = [{', '.join(js_str(l) for l in X_LABELS)}];")
lines.append(f"export const Y_LABELS = [{', '.join(js_str(l) for l in Y_LABELS)}];")
lines.append("")
lines.append("export const SCALE_AXIS_LABEL = 'Data Scale (% of CC12M)';")
lines.append("export const METRIC_AXIS_LABEL = 'Cross-Task Loss';")
lines.append("")
lines.append("export const SCALING_DATA = {")
for xi, x in enumerate(X_LABELS):
    lines.append(f"  {js_str(x)}: {{")
    for yi, y in enumerate(Y_LABELS):
        points = []
        for pct in all_pcts:
            val = graph[pct].get(x, {}).get(y)
            if val is not None:
                points.append(f"{{ x: {pct}, y: {round(val, 6)} }}")
        comma = "," if yi < len(Y_LABELS) - 1 else ""
        if points:
            lines.append(f"    {js_str(y)}: [{', '.join(points)}]{comma}")
    x_comma = "," if xi < len(X_LABELS) - 1 else ""
    lines.append(f"  }}{x_comma}")
lines.append("};")
lines.append("")
lines.append(f"export const PALETTE = [{', '.join(repr(c) for c in PALETTE)}];")
lines.append("")

output = "\n".join(lines)
with open(JS_PATH, "w") as f:
    f.write(output)

print(f"Written {JS_PATH}")
print(f"  X_LABELS ({len(X_LABELS)}): {X_LABELS}")
print(f"  Y_LABELS ({len(Y_LABELS)}): {Y_LABELS}")
print(f"  Data percentages: {all_pcts}")