import glob
import json
import re
import os


DATA_PATH = "results-base/fits"
JS_PATH = "../../src/data/scalingFitsData.js"

# 1% of CC12M = 5e9 tokens (derived from observed training scale)
N_TOKENS_PER_PCT = 5e9

PALETTE = [
    '#6c8ef5', '#f472b6', '#34d399', '#fbbf24',
    '#a78bfa', '#fb923c', '#22d3ee', '#e879f9',
]

# Preserve label ordering consistent with scalingDataBase.js
PREFERRED_X_ORDER = [
    'caption', 'det', 'rgb@224',
    'tok_clip@224', 'tok_depth@224', 'tok_normal@224', 'tok_rgb@224', 'tok_semseg@224',
]
PREFERRED_Y_ORDER = [
    'det', 'tok_clip@224', 'tok_depth@224', 'tok_normal@224',
    'tok_rgb@224', 'tok_semseg@224', 'caption',
]

# fits = { X: { Y: { E, B, beta, C } } }
fits = {}

for file in glob.glob(f"{DATA_PATH}/*/scaling_law_params.json"):
    folder = os.path.basename(os.path.dirname(file))
    # Split on _to_ — no modality name contains the substring "_to_"
    match = re.match(r"^(.+)_to_(.+)$", folder)
    if not match:
        print(f"  Skipped (cannot parse folder): {folder}")
        continue
    X = match.group(1)
    Y = match.group(2)

    with open(file) as f:
        data = json.load(f)

    params = data["parameters"]
    fits.setdefault(X, {})[Y] = params

# Build ordered X/Y label sets
def ordered_labels(all_labels, preferred):
    seen = [l for l in preferred if l in all_labels]
    rest = sorted(l for l in all_labels if l not in seen)
    return seen + rest

all_x = set(fits.keys())
all_y = set(y for ys in fits.values() for y in ys)
X_LABELS = ordered_labels(all_x, PREFERRED_X_ORDER)
Y_LABELS = ordered_labels(all_y, PREFERRED_Y_ORDER)


def js_str(s):
    return f"'{s}'"

lines = []
lines.append("/**")
lines.append(" * Scaling fits data — auto-generated by compile_fit2js.py")
lines.append(" * Parameters of L(D) = E + B / (D + C)^beta per X->Y task")
lines.append(" * D is number of training tokens; N_TOKENS_PER_PCT converts % of CC12M to tokens")
lines.append(" */")
lines.append("")
lines.append(f"export const X_LABELS = [{', '.join(js_str(l) for l in X_LABELS)}];")
lines.append(f"export const Y_LABELS = [{', '.join(js_str(l) for l in Y_LABELS)}];")
lines.append("")
lines.append(f"export const N_TOKENS_PER_PCT = {N_TOKENS_PER_PCT};")
lines.append("")
lines.append("export const SCALE_AXIS_LABEL = 'Data Scale (% of CC12M)';")
lines.append("export const METRIC_AXIS_LABEL = 'Cross-Task Loss';")
lines.append("")
lines.append("// FIT_PARAMS[X][Y] = { E, B, beta, C }  for  L(D) = E + B / (D + C)^beta")
lines.append("export const FIT_PARAMS = {")

for xi, x in enumerate(X_LABELS):
    if x not in fits:
        continue
    lines.append(f"  {js_str(x)}: {{")
    y_entries = [(y, fits[x][y]) for y in Y_LABELS if y in fits[x]]
    for yi, (y, p) in enumerate(y_entries):
        comma = "," if yi < len(y_entries) - 1 else ""
        lines.append(
            f"    {js_str(y)}: "
            f"{{ E: {p['E']}, B: {p['B']}, beta: {p['beta']}, C: {p['C']} }}{comma}"
        )
    x_comma = "," if xi < len(X_LABELS) - 1 else ""
    lines.append(f"  }}{x_comma}")
lines.append("};")
lines.append("")
lines.append(f"export const PALETTE = [{', '.join(repr(c) for c in PALETTE)}];")
lines.append("")

output = "\n".join(lines)
with open(JS_PATH, "w") as f:
    f.write(output)

print(f"Written {JS_PATH}")
print(f"  X_LABELS ({len(X_LABELS)}): {X_LABELS}")
print(f"  Y_LABELS ({len(Y_LABELS)}): {Y_LABELS}")
total = sum(len(fits[x]) for x in fits)
print(f"  Total task fits: {total}")
